/* Database schema to keep the structure of entire database. */
CREATE TABLE animals (
id INT,
name VARCHAR(50) NOT NULL ,
date_of_birth DATE NOT NULL ,
escape_attempts INT NOT NULL,
neutered boolean NOT NULL,
weight_kg decimal NOT NULL
);

/* Add new column*/
ALTER TABLE animals
ADD species VARCHAR(20);

-- Create a table named owners with columns

CREATE TABLE owners (
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
full_name VARCHAR(20) ,
age INT);

-- Create a table named species with columns
 CREATE TABLE species (
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
name VARCHAR(20));

-- Modify animals table:
   -- Make sure that id is set as autoincremented PRIMARY KEY
ALTER TABLE animals MODIFY id GENERATED BY DEFAULT AS IDENTITY;
   -- Remove column species
ALTER TABLE animals 
DROP COLUMN species
   -- Add column species_id which is a foreign key referencing species table
ALTER TABLE animals 
ADD species_id INT, ADD FOREIGN KEY(species_id) REFERENCES species(id);
   -- Add column owner_id which is a foreign key referencing the owners table
   ALTER TABLE animals 
ADD owner_id INT, ADD FOREIGN KEY(species_id) REFERENCES owners(id);



